Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "myrubygem" 
  config.vm.hostname = "myrubygem.myworld.net"

  config.vm.network "private_network", ip: "192.168.73.73"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

   config.vm.provision "shell", inline: "sed -i -e 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config"

#   config.vm.provision "shell" do |s|
#     s.path = "configure-local-yum-repo.sh"
#   end

   config.vm.provision "shell", inline: "echo Hello, Welcome to your new rubygem VM.."
end
