Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "mymaster5" 
  config.vm.hostname = "mymaster5.myworld.net"

  config.vm.network "private_network", ip: "192.168.120.120"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

   config.vm.synced_folder "control-repo", "/etc/puppetlabs/code/environments/local", create: true

   config.vm.provision "shell", inline: "sed -i -e 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config"

#   config.vm.provision "shell" do |s|
#     s.path = "configure-local-yum-repo.sh"
#   end

#   config.vm.provision "shell" do |s|
#     s.path = "install-selinux-utils.sh"
#   end

#   config.vm.provision "shell" do |s|
#     s.path = "install-puppet-agent.sh"
#   end

#   config.vm.provision "shell" do |s|
#     s.path = "create-hiera-yaml.sh"
#   end

   config.vm.provision "shell", inline: "echo Hello, Welcome to your new Puppet Master 5.0 VM.."
   config.vm.provision "shell", inline: "echo SELINUX has been set to enforcing, so please vagrant halt and up again.."
end
