Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "puppetlabs/centos-7.2-64-nocm"

  config.vm.define "my-email-vm" 
  config.vm.hostname = "my-email-vm.neverland.co.uk" 

  config.vm.network "private_network", ip: "192.168.8.80"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello, Welcome to your new Email Vagrant VM" 
   SHELL
end

