Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "my-shared-folder" 
  config.vm.hostname = "my-shared-folder"

  config.vm.network "private_network", ip: "192.168.97.97"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.synced_folder "../scripts", "/home/vagrant/scripts", create: true
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello, Welcome to your new CentOS Vagrant Folder Testing VM.." 
SHELL

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /etc/puppetlabs/code
    cp scripts/hello.txt /etc/puppetlabs/code/hiera.yaml
    chmod 644 /etc/puppetlabs/code/hiera.yaml
  SHELL
  
  config.vm.provision "shell" do |s|
    s.path = "../scripts/hello.sh"
  end

end

