Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "ftp-server" do |server|
    server.vm.hostname = "ftp-server.myworld.net"
    server.vm.network "private_network", ip: "192.168.100.100"
    server.vm.provision "shell", inline: "systemctl restart network"
    server.vm.provision "shell", inline: <<-SHELL
      echo "Hello, Welcome to your new CentOS FTP Server VM" 
SHELL
  end

  config.vm.define "ftp-client" do |client|
    client.vm.hostname = "ftp-client.myworld.net"
    client.vm.network "private_network", ip: "192.168.100.101"
    client.vm.provision "shell", inline: "systemctl restart network"
    client.vm.provision "shell", inline: <<-SHELL
      echo "Hello, Welcome to your new CentOS FTP Client VM"
SHELL
  end



end

