Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "mysftp-centos" 
  config.vm.hostname = "mysftp.myworld.net"

  config.vm.network "private_network", ip: "192.168.200.200"
  config.vm.provision "shell", inline: "sed -i -e 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello, Welcome to your new CentOS SFTP VM" 
SHELL

end

