Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "myselinux" 
  config.vm.hostname = "myselinux.myworld.net"

  config.vm.network "private_network", ip: "192.168.15.21"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Setting SELinux to enabled.."
    sed -i -e 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config
    echo "Hello, Welcome to your new CentOS Selinux VM, Good Luck!.."
    echo "Rebooting the VM...Wait for 1 minute and then login into your VM(vagrant ssh)" 
    #reboot 
SHELL

end

