Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = 'puppetlabs/centos-7.2-64-nocm'

  config.vm.define "myjira-centos" 
  config.vm.hostname = "myjira-centos"

  config.vm.network "private_network", ip: "192.168.85.85"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello, Welcome to your new CentOS Jira VM" 
SHELL

end

