Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "debian/jessie64"

  config.vm.define "my-debian-email-vm" 
  config.vm.hostname = "my-debian-email-vm.neverland.co.uk" 

  config.vm.network "private_network", ip: "192.168.90.90"
  config.vm.provision "shell", inline: "systemctl restart network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512 
    vb.cpus = 1 
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

# The following seems to throw an error, but the Debian VM seems to be setup OK.
  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello, Welcome to your new Debian Email Vagrant VM" 
   SHELL
end

